# syntax=docker/dockerfile:1

#base image
FROM openjdk:11-slim as build

#ARG WORKING_DIR
#ENV WORKING_DIR=${WORKING_DIR}

COPY .mvn/ .mvn
COPY mvnw pom.xml ./

RUN ./mvnw dependency:go-offline

COPY src ./src

CMD ["./mvnw", "spring-boot:run"]
