version: "3.8"

services:

  configserver:
    image: chughpuneet/configurations:1.0
    mem_limit: 700m
    ports:
      - "8093:8093"
    networks:
      - banking

  accounts:
    image: chughpuneet/accounts:1.0
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - banking
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8093/

  loans:
    image: chughpuneet/loans:1.0
    mem_limit: 700m
    ports:
      - "8091:8091"
    networks:
      - banking
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8093/

  cards:
    image: chughpuneet/cards:1.0
    mem_limit: 700m
    ports:
      - "8092:8092"
    networks:
      - banking
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8093/

networks:
  banking: