version: "3.8"

services:

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
      - banking

  configserver:
    image: chughpuneet/configurations_server:1.0
    mem_limit: 700m
    ports:
      - "8093:8093"
    networks:
      - banking
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  registryserver:
    image: chughpuneet/registryserver:1.0
    mem_limit: 700m
    ports:
      - "8094:8094"
    networks:
      - banking
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    environment:
      #SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8093/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  gatewayserver:
    image: chughpuneet/gatewayserver:1.0
    mem_limit: 700m
    ports:
      - "8095:8095"
    networks:
      - banking
    depends_on:
      - configserver
      - registryserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    environment:
      #SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8093/
      eureka.client.serviceUrl.defaultZone: http://registryserver:8094/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  accounts:
    image: chughpuneet/accounts:1.0
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - banking
    depends_on:
      - configserver
      - registryserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8093/
      eureka.client.serviceUrl.defaultZone: http://registryserver:8094/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  loans:
    image: chughpuneet/loans:1.0
    mem_limit: 700m
    ports:
      - "8091:8091"
    networks:
      - banking
    depends_on:
      - configserver
      - registryserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8093/
      eureka.client.serviceUrl.defaultZone: http://registryserver:8094/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  cards:
    image: chughpuneet/cards:1.0
    mem_limit: 700m
    ports:
      - "8092:8092"
    networks:
      - banking
    depends_on:
      - configserver
      - registryserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8093/
      eureka.client.serviceUrl.defaultZone: http://registryserver:8094/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

networks:
  banking: